name: Scheduler

on:
  workflow_dispatch: # 用于手动触发
  schedule:
    - cron: "0 7 * * *" # 每天 7:00 定时执行
  push:
    branches: [main]

jobs:
  update-repo-contributors:
    name: Update contributors SVG for repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm i

      - name: Run SVG generation script
        run: |
          pnpm exec gh-contrib-svg -t ${{ secrets.GITHUB_TOKEN }} -o zotero-chinese -r wiki
          pnpm exec gh-contrib-svg -t ${{ secrets.GITHUB_TOKEN }} -o zotero-chinese -r styles
          pnpm exec gh-contrib-svg -t ${{ secrets.GITHUB_TOKEN }} -o zotero-chinese -r zotero-plugins
          pnpm exec gh-contrib-svg -t ${{ secrets.GITHUB_TOKEN }} -o l0o0 -r translators_CN

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contributors for repos [skip ci]"
          add: ".github-contributors/*"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-org-contributors:
    name: Update contributors for org
    needs:
      - update-repo-contributors
    runs-on: ubuntu-latest
    steps:
      - name: Update contributors for org
        uses: thinkasany/organize-contributors@master
        with:
          organize_name: zotero-chinese
          github_token: ${{ secrets.GITHUB_TOKEN }}
          png_path: .github-contributors/contributors.png
          json_path: .github-contributors/contributors.json
          branch: main
          excludes_list: "ImgBotApp,github-actions[bot],actions-user,imgbot[bot],dependabot[bot],renovate[bot]"
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          commit_message: "chore: update contributors for org [skip ci]"

  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm i

      - name: Update sponsors
        run: pnpm update-sponsors
        env:
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore: update sponsors.svg [skip ci]"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
